jt808:
  print-component-statistics: true
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
  entity-scan:
    enabled: true
    enable-builtin-entity: true
    base-packages:
  handler-scan:
    base-packages:
  msg-processor:
    thread-pool:
      # core-pool-size: Runtime.getRuntime().availableProcessors() + 1
      # maximum-pool-size: 2 * corePoolSize
      keep-alive-time: 60s
      blocking-queue-size: 20
      thread-name-format: '808-msg-processor-%d'