server:
  port: 8808
jt808:
  print-component-statistics: true
  entity-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.annotation.entity.req
    enable-builtin-entity: true
  handler-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.annotation.handler
logging:
  level: info
  level.io.github.hylexus: debug
  level.jt-808.msg.req.decoder: debug