server:
  port: 8808
jt808:
  print-component-statistics: true
  entity-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.annotation.entity.req
    enable-builtin-entity: true
    register-builtin-request-msg-converters: true
  handler-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.annotation.handler
    register-builtin-msg-handlers: true
  exception-handler-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.annotation.handler
    register-builtin-exception-handlers: true
logging:
  level: info
#  level.io.github.hylexus: debug
#  level.jt-808.msg.req.decoder: debug
#  level.jt-808.msg.req.handler.abstract-msg-handler: info